extends:
  [
    'stylelint-config-standard',
    'stylelint-config-prettier',
    'stylelint-prettier/recommended'
  ]
plugins: ['stylelint-scss']
# ignoreFiles: ["dist/**/*.css"]
rules:
  color-function-notation: "legacy"
  at-rule-no-unknown: null
  declaration-empty-line-before: null
  scss/at-rule-no-unknown: true
  scss/dollar-variable-pattern: "^color"
  # scss/selector-no-redundant-nesting-selector: true
  selector-class-pattern: null
  alpha-value-notation: "number"

overrides: [{
  files: ['**/*.scss'],
  customSyntax: "postcss-scss"
}]
